### ISSUE TITLE
Longer sequence generation.

### ISSUE THREAD

**Issue by sambalshikhar** [VITA-MLLM/Freeze-Omni#8]
Since the speech decoder is disjoint from the LLM , how does it handle generating speech tokens beyond the context length of the speech decoder.As the LLM might generate longer sequences and the speech decoder might predict end of speech token before.

**Comment by wangxiongts** [comment]
As described in the paper and related content in the code, we split the context output by the LLM through a sentence split strategy. The predicted length of the generating speech tokens will depend on when the speech decoder outputs the <eos> token. This process completely depends on the robustness of the speech decoder. Generally speaking, due to the large amount of data training, the output position of this <eos> token is usually reasonable.
